apiVersion: v1
kind: Pod
metadata:
  name: config-map-pod
spec:
  containers:
    - name: test
      image: busy-box
      volumeMounts:
        - name: config-vol
          mountPath: /etc/config
  volumes:        
    - name: config-vol
      configMap:
        name: log-config
        items:
          - key: log_level
            path: log_level          

